export { default as Footer } from "./Footer";
export { default as FirstSection } from "./FirstSection";
export { default as SecondSection } from "./SecondSection";
export { default as Hero } from "./Hero";
export { default as Testimonial } from "./Testimonial";
export { default as Navbar } from "./Navbar";
export { default as Layout } from "./Layout";
export { default as Post } from "./Post";
export { default as Contact } from "./Contact";